env:
    browser: true
    es6: true
    node: true
settings:
    react:
        version: detect
extends:
    - eslint:recommended
    - plugin:react/recommended
parser: babel-eslint
parserOptions:
    ecmaFeatures:
        jsx: true
    ecmaVersion: 2018
    sourceType: module
plugins:
    - react
rules:
    indent: 0
    linebreak-style:
        - error
        - unix
    quotes:
        - error
        - single
    semi:
        - error
        - always
